### ISSUE TITLE
Can't load unedited RigidBody JSON file. KeyError: None

### ISSUE THREAD

**Issue by GingerAvalanche** [krenyy/botw_havok#3]
Trying to do the following:
```
hk0 = Havok.from_file(path)
hk.deserialize()
hk.to_json(other_path)

hk1 = Havok.from_json(other_path)
```
gives me the following error for a bunch of vanilla files:
```
Traceback (most recent call last):
  File "d:\python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "d:\python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "d:\python37\lib\site-packages\hyrule_builder\builder.py", line 167, in _build_json
    hk = Havok.from_json(f)
  File "d:\python37\lib\site-packages\botw_havok\havok.py", line 129, in from_json
    return cls.from_dict(json.load(f), Path(path))
  File "d:\python37\lib\site-packages\botw_havok\havok.py", line 122, in from_dict
    inst.files = [HKFile.from_dict(file) for file in l]
  File "d:\python37\lib\site-packages\botw_havok\havok.py", line 122, in <listcomp>
    inst.files = [HKFile.from_dict(file) for file in l]
  File "d:\python37\lib\site-packages\botw_havok\hkfile.py", line 108, in from_dict
    inst.data = HKDataSection.from_dict(d["data"])
  File "d:\python37\lib\site-packages\botw_havok\container\sections\data\hkdatasection.py", line 223, in from_dict
    for content in d["contents"]
  File "d:\python37\lib\site-packages\botw_havok\container\sections\data\hkdatasection.py", line 223, in <listcomp>
    for content in d["contents"]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkRootLevelContainer.py", line 100, in from_dict
    hkRootLevelContainerNamedVariant.from_dict(nv) for nv in d["namedVariants"]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkRootLevelContainer.py", line 100, in <listcomp>
    hkRootLevelContainerNamedVariant.from_dict(nv) for nv in d["namedVariants"]
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkRootLevelContainerNamedVariant.py", line 69, in from_dict
    inst.variant = class_map.HKClassMap.get(d["className"]).from_dict(d["variant"])
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpPhysicsData.py", line 117, in from_dict
    inst.systems = [hkpPhysicsSystem.from_dict(ps) for ps in d["systems"]]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpPhysicsData.py", line 117, in <listcomp>
    inst.systems = [hkpPhysicsSystem.from_dict(ps) for ps in d["systems"]]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpPhysicsSystem.py", line 188, in from_dict
    inst.rigidBodies = [hkpRigidBody.from_dict(rb) for rb in d["rigidBodies"]]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpPhysicsSystem.py", line 188, in <listcomp>
    inst.rigidBodies = [hkpRigidBody.from_dict(rb) for rb in d["rigidBodies"]]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpRigidBody.py", line 35, in from_dict
    inst.__dict__.update(hkpEntity.from_dict(d).__dict__)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpEntity.py", line 229, in from_dict
    inst.__dict__.update(super().from_dict(d).__dict__)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpWorldObject.py", line 128, in from_dict
    inst.collidable = hkpLinkedCollidable.from_dict(d["collidable"])
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpLinkedCollidable.py", line 43, in from_dict
    inst.__dict__.update(super().from_dict(d).__dict__)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpCollidable.py", line 72, in from_dict
    inst.__dict__.update(super().from_dict(d).__dict__)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpCdBody.py", line 83, in from_dict
    d["shape"]
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpListShape.py", line 109, in from_dict
    inst.__dict__.update(hkpShapeCollection.from_dict(d).__dict__)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpShapeCollection.py", line 53, in from_dict
    inst.collectionType = CollectionType[d["collectionType"]]
  File "d:\python37\lib\enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: None
```

The files in question are all inside actor packs, of the same name as their hkrb file.
```
content/Physics/RigidBody/Obj_TreePalmCoconut_A/Obj_TreePalmCoconut_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeBurned_A/Obj_TreeBurned_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous_C/Obj_TreeConiferous_C_01.hkrb.json
content/Physics/RigidBody/TwnObj_Village_RitoGuidePost_A/TwnObj_Village_RitoGuidePost_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeApple_A/Obj_TreeApple_A_L_01.hkrb.json
content/Physics/RigidBody/Obj_TreeDead_A/Obj_TreeDead_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeBroadleaf_B/Obj_TreeBroadleafDead_B_L_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_04.hkrb.json
content/Physics/RigidBody/Obj_TreePine_A/Obj_TreePine_A_01.hkrb.json
content/Physics/RigidBody/TwnObj_Village_RitoGuidePost_A/TwnObj_Village_RitoGuidePost_A_03.hkrb.json
content/Physics/RigidBody/Obj_TreeBanana_A/Obj_TreeBanana_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreePalmCoconut_A/Obj_TreePalmCoconut_A_02.hkrb.json
content/Physics/RigidBody/TwnObj_Village_HatenoGuidePost_A/TwnObj_Village_AncientCivilLaboSignboard_A_01.hkrb.json
content/Physics/RigidBody/FldObj_SignboardWood_A/FldObj_SignboardWood_A_01_Trunk.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_01.hkrb.json
content/Physics/RigidBody/TwnObj_Village_HatenoGuidePost_A/TwnObj_Village_HatenoGuidePost_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferousDead_A/Obj_TreeConiferousDead_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeBurned_B/Obj_TreeBurned_B_01.hkrb.json
content/Physics/RigidBody/Obj_TreeDragonblood_A/Obj_TreeDragonblood_A_03.hkrb.json
content/Physics/RigidBody/Obj_TreeDorian_A/Obj_TreeDorian_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous_C/Obj_TreeConiferous_C_02.hkrb.json
content/Physics/RigidBody/Obj_TreePalm_A/Obj_TreePalm_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeGhost_A/Obj_TreeGhost_A_03.hkrb.json
content/Physics/RigidBody/Obj_TreeBurned_B/Obj_TreeBurned_B_02.hkrb.json
content/Physics/RigidBody/Obj_TreeWhiteBirch_A/Obj_TreeWhiteBirch_A_02.hkrb.json
content/Physics/RigidBody/FldObj_SignboardWood_A/FldObj_SignboardWood_A_02_Trunk.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous_C/Obj_TreeConiferous_C_03.hkrb.json
content/Physics/RigidBody/Obj_TreeWhiteBirch_A/Obj_TreeWhiteBirch_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeMaple_A/Obj_TreeMaple_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreePalm_A/Obj_TreePalm_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeWillow_A/Obj_TreeWillow_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferousDead_A/Obj_TreeConiferousDead_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeBroadleaf_A/Obj_TreeBroadleaf_A_L.hkrb.json
content/Physics/RigidBody/Obj_TreeMaple_A/Obj_TreeMaple_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_03.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferousSnow_A/Obj_TreeConiferous_A_Snow_03.hkrb.json
content/Physics/RigidBody/Obj_TreeApple_A/Obj_TreeApple_A_M_01.hkrb.json
content/Physics/RigidBody/Obj_TreeDeadLeaf_A/Obj_TreeDeadLeaf_A_01.hkrb.json
```

**Comment by krenyy** [comment]
Fixed in db72270df59d3c51dbc141bff7a92ea8448ea38a
