### ISSUE TITLE
Unable to serialize unedited Havok JSON files after loading. KeyError: 'hkpListShape'

### ISSUE THREAD

**Issue by GingerAvalanche** [krenyy/botw_havok#5]
As a result of https://github.com/krenyy/botw_havok/commit/db72270df59d3c51dbc141bff7a92ea8448ea38a I can now get the files from #3 loaded back into memory.

However, when serializing them, I get the following error:
```
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\botw_havok\classes\util\signature_map.py", line 62, in get
    return HKSignatureMap.hk_signature_map[name]
KeyError: 'hkpListShape'
```
That doesn't seem very explanatory to me, but there was a second error that occurred during handling of that one that might shed more light on it:
```
Traceback (most recent call last):
  File "d:\python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "d:\python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "d:\python37\lib\site-packages\hyrule_builder\builder.py", line 174, in _build_json
    hk.serialize()
  File "d:\python37\lib\site-packages\botw_havok\havok.py", line 35, in serialize
    file.serialize()
  File "d:\python37\lib\site-packages\botw_havok\hkfile.py", line 57, in serialize
    self.data.serialize(self)
  File "d:\python37\lib\site-packages\botw_havok\container\sections\data\hkdatasection.py", line 113, in serialize
    hkFile, BinaryWriter(big_endian=hkFile.header.endian == 0), obj,
  File "d:\python37\lib\site-packages\botw_havok\classes\hkRootLevelContainer.py", line 84, in serialize
    hkFile, BinaryWriter(big_endian=hkFile.header.endian == 0), gr.dst_obj
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpPhysicsData.py", line 94, in serialize
    hkFile, BinaryWriter(big_endian=hkFile.header.endian == 0), gr.dst_obj
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpPhysicsSystem.py", line 153, in serialize
    gr.dst_obj,
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpRigidBody.py", line 22, in serialize
    hkpEntity.serialize(self, hkFile, bw, obj)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpEntity.py", line 129, in serialize
    super().serialize(hkFile, bw, obj)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpWorldObject.py", line 94, in serialize
    self.collidable.serialize(hkFile, bw, obj)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpLinkedCollidable.py", line 28, in serialize
    super().serialize(hkFile, bw, obj)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpCollidable.py", line 40, in serialize
    super().serialize(hkFile, bw, obj)
  File "d:\python37\lib\site-packages\botw_havok\classes\common\hkpCdBody.py", line 60, in serialize
    hkFile, BinaryWriter(big_endian=hkFile.header.endian == 0), gr.dst_obj,
  File "d:\python37\lib\site-packages\botw_havok\classes\hkpListShape.py", line 60, in serialize
    HKBaseClass.assign_class(self, hkFile, obj)
  File "d:\python37\lib\site-packages\botw_havok\classes\base.py", line 26, in assign_class
    obj.hkClass = hkFile.classnames.get(self.hkClass)
  File "d:\python37\lib\site-packages\botw_havok\container\sections\classnames\hkclassnamessection.py", line 87, in get
    cls = HKClass.from_name(value)
  File "d:\python37\lib\site-packages\botw_havok\container\sections\classnames\hkclass.py", line 32, in from_name
    inst.signature = HKSignatureMap.get(name)
  File "d:\python37\lib\site-packages\botw_havok\classes\util\signature_map.py", line 64, in get
    raise Exception(f"Missing signature for class '{name}'")
Exception: Missing signature for class 'hkpListShape'
```
It happens for the following files:
```
content/Physics/RigidBody/Obj_TreeConiferous_C/Obj_TreeConiferous_C_03.hkrb.json
content/Physics/RigidBody/Obj_TreeDead_A/Obj_TreeDead_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferousDead_A/Obj_TreeConiferousDead_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferousDead_A/Obj_TreeConiferousDead_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferousSnow_A/Obj_TreeConiferous_A_Snow_03.hkrb.json
content/Physics/RigidBody/Obj_TreeApple_A/Obj_TreeApple_A_L_01.hkrb.json
content/Physics/RigidBody/TwnObj_Village_RitoGuidePost_A/TwnObj_Village_RitoGuidePost_A_03.hkrb.json
content/Physics/RigidBody/Obj_TreePine_A/Obj_TreePine_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreePalmCoconut_A/Obj_TreePalmCoconut_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeWhiteBirch_A/Obj_TreeWhiteBirch_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeDorian_A/Obj_TreeDorian_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreePalmCoconut_A/Obj_TreePalmCoconut_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeWillow_A/Obj_TreeWillow_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeWhiteBirch_A/Obj_TreeWhiteBirch_A_01.hkrb.json
content/Physics/RigidBody/TwnObj_Village_HatenoGuidePost_A/TwnObj_Village_AncientCivilLaboSignboard_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreePalm_A/Obj_TreePalm_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeBurned_B/Obj_TreeBurned_B_01.hkrb.json
content/Physics/RigidBody/Obj_TreeBurned_A/Obj_TreeBurned_A_01.hkrb.json
content/Physics/RigidBody/FldObj_SignboardWood_A/FldObj_SignboardWood_A_01_Trunk.hkrb.json
content/Physics/RigidBody/Obj_TreeBroadleaf_A/Obj_TreeBroadleaf_A_L.hkrb.json
content/Physics/RigidBody/Obj_TreeBurned_B/Obj_TreeBurned_B_02.hkrb.json
content/Physics/RigidBody/Obj_TreePalm_A/Obj_TreePalm_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_04.hkrb.json
content/Physics/RigidBody/Obj_TreeBroadleaf_B/Obj_TreeBroadleafDead_B_L_01.hkrb.json
content/Physics/RigidBody/Obj_TreeMaple_A/Obj_TreeMaple_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous/Obj_TreeConiferous_A_03.hkrb.json
content/Physics/RigidBody/Obj_TreeDeadLeaf_A/Obj_TreeDeadLeaf_A_01.hkrb.json
content/Physics/RigidBody/TwnObj_Village_RitoGuidePost_A/TwnObj_Village_RitoGuidePost_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeApple_A/Obj_TreeApple_A_M_01.hkrb.json
content/Physics/RigidBody/Obj_TreeMaple_A/Obj_TreeMaple_A_02.hkrb.json
content/Physics/RigidBody/Obj_TreeDragonblood_A/Obj_TreeDragonblood_A_03.hkrb.json
content/Physics/RigidBody/TwnObj_Village_HatenoGuidePost_A/TwnObj_Village_HatenoGuidePost_A_01.hkrb.json
content/Physics/RigidBody/Obj_TreeBanana_A/Obj_TreeBanana_A_01.hkrb.json
content/Physics/RigidBody/FldObj_SignboardWood_A/FldObj_SignboardWood_A_02_Trunk.hkrb.json
content/Physics/RigidBody/Obj_TreeConiferous_C/Obj_TreeConiferous_C_03.hkrb.json
```

**Comment by krenyy** [comment]
The initial class signature dump was incomplete, fixed in 5182b19db5055819027a94ea36ccc5c9249c798b.
